### ISSUE TITLE
Dimension is not matching

### ISSUE THREAD

**Issue by jeong-tae** [kevinzakka/recurrent-visual-attention#1]
Currently i am working on making a RAM with pytorch.
i found your code and following now.

https://github.com/kevinzakka/recurrent-visual-attention/blob/master/modules.py#L164
in this line, the phi is 4D tensor if given image is color, otherwise 3D
Whatever it should be 2D tensor to apply linear operation.

isn't it a typo? or missing a reshape?

**Comment by kevinzakka** [comment]
Hey @jeong-tae, my repo is still unfinished. It's missing full support for batched images (i.e. 4D tensors) and I still have not coded the REINFORCE algorithm. I made it public because I was hoping to get help with a bounding box issue that was occurring.

**Comment by duygusar** [comment]
I suppose this was a mistake of mine to start with as I don't have experience with pytorch. @kevinzakka  thank you for sharing your code but could you add a note of known issues or not yet supported parts. I have been trying to make it run on my custom RGB dataset to no avail. If/When I have more experience with pytorch I can work it around but it gave me the impression that this is a complete implementation of the paper so I was convinced it was my dataloader.

**Comment by kevinzakka** [comment]
@duygusar I fail to see how my README conveys the impression that this is a fully implemented version of the paper. There is an unfinished **TODO** list and the **Results** section clearly states that only the `28x28` MNIST was tackled. On top of that, the authors of the paper only worked with `28x28` and `60x60` square images. Strictly speaking then, any deviation from that would entail not being a "full-implementation" of the paper. 

If I understand correctly, you want me to add a note in the README mentioning that rectangular images may throw a runtime error?
