### ISSUE TITLE
IndexError: invalid index of a 0-dim tensor. Use tensor.item() to convert a 0-dim tensor to a Python number

### ISSUE THREAD

**Issue by Curry30h** [kevinzakka/recurrent-visual-attention#21]
use pytorch 1.0 python3.7

**Comment by GilbertZhang** [comment]
same issue here, did you find a solution Mr. Curry?

**Comment by ifgovh** [comment]
I use Python 3.6.5 and also meet this problem.

**Comment by ifgovh** [comment]
I found the solution here: https://github.com/pytorch/pytorch/issues/15585#issuecomment-450307685
