### ISSUE TITLE
pytorch version

### ISSUE THREAD

**Issue by zhujiagang** [kevinzakka/recurrent-visual-attention#6]
Thank you for this repo! 
Which version of pytorch are you using exactly?
```
import torch
print(torch.__version__)
```
After running this code, mine is `0.2.0_4`. There are many errors when I try to run yor code, include variable shape like https://github.com/kevinzakka/recurrent-visual-attention/blob/3828ad9a04b88e18456b8a498ca6dc2eb8c7cebb/trainer.py#L220
and https://github.com/kevinzakka/recurrent-visual-attention/blob/3828ad9a04b88e18456b8a498ca6dc2eb8c7cebb/model.py#L6

**Comment by kevinzakka** [comment]
Hey,

Try running the code on 0.3.1 which is the one you would get by installing using the instructions posted on http://pytorch.org/.

Cheers

**Comment by zhujiagang** [comment]
@kevinzakka Thank you! It works with python3.5 and pytorch 0.3.1.

**Comment by kevinzakka** [comment]
Sweet, I've updated the README to reflect the correct pytorch version :)
