### ISSUE TITLE
(Possibly) faster retina

### ISSUE THREAD

**Issue by ipod825** [kevinzakka/recurrent-visual-attention#9]
https://github.com/kevinzakka/recurrent-visual-attention/blob/b659b6ff06561d073320b8123811ee738f968d9f/modules.py#L10

Just FYI, I am re-factoring your code and found that the retina network can be made a little faster by padding the whole batch with sufficient 0s and then extracting the patches directly. You can check a working version [here](https://github.com/ipod825/recurrent-visual-attention/blob/596d1bdd2e0531b1812143ad7cdd385a7723cba0/modules.py#L52).

p.s. I didn't do much profile, just check the time for the first epoch several times (about 1.3 times faster).

**Comment by varghesealex90** [comment]
@ipod825  @kevinzakka  Our group tried out both the implementations. On the MNIST data, the code provided by @kevinzakka  runs approximately @ 1000 iters/sec. However, switching the code to gpu, the code runs at 250-300 iter/sec. The trick suggested by @ipod825  helps in attaining 1000 iter/s when run on GPU.
